## 1. Create a null vector of size 10 but the fifth value which is 1.



In [1]:
import numpy as np

In [7]:
null_vector=(np.arange(10)==4).astype(int)
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2. Create a vector with values ranging from 10 to 49.

In [8]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
vect_3=np.arange(0,9).reshape(3,3)
vect_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [15]:
vect_index=np.array([1,2,0,0,4,0])
vect_index[vect_index>0]

array([1, 2, 4])

 ## 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [24]:
import random
a=np.random.randint(0,100,(10,10))
print(a)
print("MIN ",a.min())
print("MAX ",a.max())

[[70 65 76  4 46 61  6 55 60 48]
 [49 39 29 32 56 26 27 15 13 15]
 [34 56 65 61  4 13 27 68  6 73]
 [60 13 79 18 32 71 33 61 66 89]
 [12 17 46 70 80 59 63 81 80 51]
 [35  2 36  5 33  1 65 32 79 25]
 [ 3 53 32 75 88 58 68 76 82 65]
 [20 29 61 98 14 25 30  4 96  2]
 [75 65 77 13 70 24 48 64 13 80]
 [61 10  8 11 32 99 25 33 12 39]]
MIN  1
MAX  99


## 6. Create a random vector of size 30 and find the mean value.

In [30]:
d=np.arange(30)
print(d)
print('Mean',d.mean())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Mean 14.5
